---
title: "quiz2"
author: "HyeongHwan Kim"
date: "2023-11-28"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(readr)
library(stringr)
library(nycflights13)
library(data.table)
```

# Q1  

```{r}
holiday <- read_csv("holiday.csv")
```

```{r}
head(holiday, 3)
```

## 1-1  

```{r}
sum(str_detect(holiday$name, "Birthday"))
```
## 1-2  

```{r}
head(flights, 3)
```


```{r}
merge_df <- left_join(holiday, flights, by = c("year", "month", "day"))
```

```{r}
my_table <- merge_df %>%
  filter(type == "Federal Holiday") %>%
  group_by(name) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
print(my_table)
```

# Q2  

```{r}
mbti <- read_delim("raw_MBTI.txt", col_names = FALSE, del = ",")
mbti <- transpose(mbti)
```

```{r}
mbti <- mbti %>%
  mutate(Man = sapply(str_split(mbti$V1, "-"), "[[", 1), Woman = sapply(str_split(mbti$V1, "-"), "[[", 2)) %>%
  select(Man, Woman)
```

```{r}
couple_MBTI <- mbti %>%
  as_tibble()
head(couple_MBTI, 5)
```


```{r}
mat <- as.matrix(table(couple_MBTI))
rownames(mat) <- as.factor(rownames(mat))

rownames(mat) <- factor(rownames(mat), levels = levels(rownames(mat))[c(15, 16, 8, 7, 13, 14, 6, 5, 9, 10, 2, 1, 11, 12, 4, 3)])
levels(rownames(mat))
# reorder(mat, mbti_vec)
# mbti_vec <- c("ISTJ", "ISTP", "ESTP", "ESTJ", "ISFJ", "ISFP", "ESFP", "ESFJ", "INFJ", "INFP", "ENFP", "ENFJ", "INTJ", "INTP", "ENTP", "ENTJ")
# rownames(mat) <- mbti_vec
heatmap(table(couple_MBTI))
```

```{r}
matched_df <- couple_MBTI %>%
  mutate(Man_EI = sapply(str_split(Man, ""),"[[",1),
         Man_NS = sapply(str_split(Man, ""),"[[",2),
         Man_TF = sapply(str_split(Man, ""),"[[",3),
         Man_JP = sapply(str_split(Man, ""),"[[",4),
         Woman_EI = sapply(str_split(Woman, ""),"[[",1),
         Woman_NS = sapply(str_split(Woman, ""),"[[",2),
         Woman_TF = sapply(str_split(Woman, ""),"[[",3),
         Woman_JP = sapply(str_split(Woman, ""),"[[",4)) %>%
  mutate(matched = as.numeric(Man_EI==Woman_EI) + as.numeric(Man_NS==Woman_NS) + as.numeric(Man_TF==Woman_TF) + as.numeric(Man_JP==Woman_JP)) %>%
  mutate(matched = as.integer(matched)) %>%
  group_by(matched) %>%
  summarise(n = n()) %>%
  as_tibble()

print(matched_df)
```
```{r}
expected_df <- data.frame(matched = c(0, 1, 2, 3, 4), p = c(1/16, 4/16, 6/16, 4/16, 1/16))
expected_df <- expected_df %>%
  mutate(n = 30000*p) %>%
  select(matched, n)
```

```{r}
expected_df
```
```{r}
test_stat <- sum((matched_df$n - expected_df$n)^2 / (expected_df$n))
1 - pchisq(test_stat, df = 4)
```
p-value 값이 0에 매우 가까우므로, 기대도수와 관측도수가 다르다고 볼 수 있다. 즉, 영향을 미친다.

# Q3  

```{r}
head(starwars, 3)
```
```{r}
digit_name <- str_subset(starwars$name, "[0-9]+")
print(digit_name)
```
```{r}
starwars %>%
  mutate(vowel_count = str_count(str_to_lower(name), "[a|e|i|o|u]"), length = str_length(name)) %>%
  group_by(vowel_count) %>%
  summarise(n = n(), mean = mean(length))

```
모음 개수가 늘어날수록 대체로 단어의 평균 길이가 점점 증가함을 알 수 있다. 단, 모음의 개수가 0개일 때와 1개일 때는 오히려 감소한다.  
