---
title: "samplequiz2"
author: "HyeongHwan Kim"
date: "2023-11-27"
output: html_document
---

# Problem 1  

```{r}
library(tidyverse)
library(nycflights13)
```

```{r}
flights
```

```{r}
load(file = "holiday.RData")
holiday
```

```{r}
merge_df <- right_join(flights, holiday, by = c("year", "month", "day"))
head(merge_df, 3)
```

```{r}
ans1 <- merge_df %>%
  group_by(year, month, day, name) %>%
  summarise(count = n())
ans1 <- ans1 %>%
  arrange(desc(count))
```

```{r}
ans1 <- ans1 %>%
  ungroup() %>%
  select(name, count)
ans1 <- ans1 %>%
  mutate(count = as.double(count)) %>%
  as.tibble()
print(ans1)
```

# Problem 3  

```{r}
load("trees.RData")
```
```{r}
head(trees, 3)
```

```{r}
library(lubridate)
```
```{r}
library(stringr)
```


```{r}
my_ymd_hms <- function(datetime_str) {
  h <- datetime_str %>%
    str_split(" ")
  
  if(h[[1]][4] == "오후") {
    if(h[[1]][5] != "12시")
      hour <- str_extract(h[[1]][5], pattern = "^[0-9]+")
      hour <- as.numeric(hour) + 12
      h[[1]][5] <- str_c(hour, "시")
  }
  if(h[[1]][4] == "오전" && h[[1]][5] == "12시")
    h[[1]][5] <- "0시"
  
  if(h[[1]][8] == "KST")
    utc = "Asia/Seoul"
  if(h[[1]][8] == "JST")
    utc = "Asia/Tokyo"
  if(h[[1]][8] == "CST")
    utc = "Asia/Shanghai"
  h <- c(h[[1]][1:3], h[[1]][5:7])
  h <- str_c(h, collapse = " ")
  return(ymd_hms(h, tz = utc))
}
my_ymd_hms("2017년 6월 3일 오전 12시 0분 0초 JST")
```


# Part 1  

```{r}
library(readr)
```


```{r}
red_data <- read_delim("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", del = ";")
```
```{r}
white_data <- read_delim("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", del = ";")
```

```{r}
red_data <- red_data %>%
  mutate(type = "red")
```

```{r}
white_data <- white_data %>%
  mutate(type = "white")
```
```{r}
set.seed(2021)

white_sampled_data <-
  white_data %>%
  sample_n(size = nrow(red_data), replace = FALSE)

wine_data <- rbind(white_sampled_data, red_data)
```

```{r}
wine_data <- wine_data %>%
  mutate(type = as.factor(type), quality = as.factor(quality))
```



```{r}

```

