---
title: "samplequiz"
author: "HyeongHwan Kim"
date: "2023-11-05"
output: html_document
---



```{r}
library(tidyverse)
heart_disease_columns <- c(
  "age",      # age in years
  "sex",      # sex
              # - 1 = male
              # - 0 = female
  "cp",       # chest pain type
              # - 1 = typical angina
              # - 2 = atypical angina
              # - 3 = non-anginal pain
              # - 4 = asymptomatic
  "trestbps", # resting blood pressure (in mm Hg on admission to the hospital)
  "chol",     # serum cholestoral in mg/dl
  "fbs",      # fasting blood sugar > 120 mg/dl
              # - 1 = true
              # - 0 = false
  "restecg",  # resting electrocardiographic results
              # - 1 = normal
              # - 2 = having ST-T wave abnormality
              # - 3 = showing probable or definite left ventricular hypertrophy
  "thalach",  # maximum heart rate achieved
  "exang",    # exercise induced angina
              # - 1 = yes
              # - 0 = no
  "oldpeak",  # ST depression induced by exercise relative to rest
  "slope",    # the slope of the peak exercise ST segment
              # - 1 = upsloping
              # - 2 = flat
              # - 3 = downsloping
  "ca",       # number of major vessels (0-3) colored by flourosopy
  "thal",     # thal
              # - 3 = normal
              # - 6 = fixed defect
              # - 7 = reversable defect
  "num"       # diagnosis of heart disease (angiographic disease status)
              # - 0 = (< 50% diameter narrowing)
              # - 1 = (> 50% diameter narrowing)
              # - 2 = ?
              # - 3 = ?
              # - 4 = ?
)
heart_disease <- read_csv("processedï¼1.cleveland.data", col_types = cols(),
  col_names = heart_disease_columns, na = c("?")) %>%
  mutate(
    sex = factor(sex),
    cp = factor(cp),
    fbs = fbs > 0.5,
    restecg = factor(restecg),
    exang = exang > 0.5,
    slope = factor(slope),
    ca = as.integer(ca),
    thal = factor(thal),
    num = factor(num)
  )
```

# Problem 1  

```{r}
heart_disease
```
```{r}
library(ggplot2)
library(dplyr)
```

```{r}

```


```{r}

new_heart <- heart_disease %>%
  filter(rank(desc(age))==1)

ggplot() +
  geom_point(data = heart_disease, mapping = aes(x = trestbps, y = num, col = cp)) +
  facet_wrap(~thal) +
  theme(legend.position = 'bottom') +
  scale_x_reverse(limits = c(200, 100)) +
  geom_point(data = new_heart, mapping = aes(x = trestbps, y = num), col = "black")
  
```
# Problem 2  

```{r}

heart_disease %>%
  group_by(cp) %>%
  summarise(n = n())
```

```{r}
my_df <- heart_disease %>%
  group_by(sex) %>%
  filter(cp == 4) %>%
  summarise(n = n())
  
my_df$mean_age = mean(heart_disease$age)
my_df$most_common_cp_type = 4

my_df <- my_df %>%
  select(sex, mean_age, most_common_cp_type, n)

my_df$most_common_cp_type <- as.integer(my_df$most_common_cp_type)

my_df
```

# Problem 3  

```{r}
ggplot(data = heart_disease, mapping = aes(x = age, y = chol)) +
  geom_point() +
  geom_smooth(method = "lm", col = "black")
```

```{r}
ggplot(data = heart_disease, mapping = aes(x = age, y = chol)) +
  geom_point(mapping = aes(col = num)) +
  facet_wrap(~num, nrow = 1)+
  geom_smooth(method = "lm", col = "black")
```

